language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  app: damp-mesa-79990
  api_key:
    secure: 4+SZjlTxeVajCFR2aEsY+2A239c7CDHUTI+31o6hAPxcUXEKijwCNzH3tKuubvQaObiwbHPiyJupweIX197mvmK+9RywztcoENJyXnhKsLPEVoW50mxcoierbIfjaBZ3kiqm4lPOvlbrm9qXSmVzFJq9E1jAmSPCGYYeyadJtg1mbkpLUk5uCiwOjd8zWb+WHyy5ZSvmhe7dmQFcQu39n+KpEFVVoGGUqGMptlo69+eTJLnbB6+/xJKPkLAANeT2yQZDsu6ees/NYIIws3Gf7BB6UOxSs1JDC3qDRjFfAeqOjcYUt6XMYmZc7Q+w38SWTBpG6PP9lFPaHy4oNNRN+uxGIAfdoTkQOlgnvaRmcxlgj/Cnb+p6Mf/JMfwuxrJ9mbhI7/sDopo1z3cpAXy+1RBw89kZcY2tV9/GCDaJapUyTOAlWQ96WDDbNmW0LkI6Vgm7QTf2oTuc568Wjbe+JABgRZR6Kr+rqmWxw/oWR8QPNS70mRxwFDdeTovi/pP/m2N1QG4qEKlTHMqvZLTIvl9lwPvb/N9j1oqKj2p0jYahzToMDMu3YVN/Cr8ruUFSOF6hAMt9oCi1azYFC9CEGeFYG9UEtg6OOQf4HHgCHpPkrjNWAtaiWWU/NcbZZzBO3/RHAlL0nP83vAjwrTBunm6JnTKUn5+Jv2qVvwnr4mM=
