language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  app: damp-mesa-79990
  api_key:
    secure: SNwF0SgxjLSH4Fr99fkZUBRR7oexVh4Cf0fZbWQYhhbosDYoCEPJM93dqSLRBD3/DdOueejZByu4cOW0OqzXbo+Z/YOHppN9vC1u/YnFtrGC21LtLzbA/9UdAN9idCH9C7xmnlf/F4HmpTQw38SOV4xuGaOVvOxnrsRY71BVAVBxxverplaiXigfUf+7+/hKklfKy07UjoXmfNKJYn0dd5LCqmlNSMYYnPsjy2bHNh2eUxMffSkD1FX4TfLZ5enluAyPVl9YBeT9CDSUcz6QyH3+BmWkVFVgW9ScHWpDg77zlT0MDMLRAq0dbBXifarJm68U33wNbPCS5pe6b+6VCsGQ25X0cfOPZFT6Z9DfH9TICD5YgvEWoG+tDj92XGwFOlKFXKu0W9s0livcvDvLS8ix7VmHX0yke6aDwB7Mq4MH2oYiOx2PUEJv42O+z9zS7qbBdOCXp9+c9RYgEZDIOaTPw5H7QO5TyxVltwup092rM5oCryC7kyBgqXVhZfYIZa1ncnz2Rn2klayeA069VfXoZEMr2Ofp5k4z6XXLLZwDfpAyChmOtz1HmU/Iq3HpoafzziQEoY1tE/8pBV5iGO8yA+MbnxzB8ERWNqNfsBP0WJ4i6Ra9Ou1GPtDj/7kbubmiZmQdC+/SfGGb8GkdW6MBFHkyRQrg2erWlRKj49U=
